name: initial
run-name: this is an initial action for this repo
on:
  push:
    branches:
      - main

jobs:
  created-new-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if 'test' branch exists and create if necessary
        run: |
          if git rev-parse --verify --quiet test; then
            echo "Branch 'test' already exists."
          else
            echo "Branch 'test' does not exist. Creating branch."
            git checkout -b test
            git push origin test
          fi
