name: initial
run-name: this is a initial action for this repo
on: 
  push:
    branches: 
      - main

jobs:
   created-new-branch:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout the repository
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }} 

       - name: Create a new branch 'test'
         run: |
            git checkout -b test
            git push origin test
         

       

